### ISSUE TITLE
Able to Spawn in Mushroom Fields

### ISSUE THREAD

**Issue by Kronon-Conspirator** [Safrodev/Zombified#2]
As the title says, the zombies still spawn in mushroom fields which in vanilla should be only exclusive to mooshrooms. I know this could be a "its a feature not a bug" situation but would like a toggle in the configs at least

**Comment by Safrodev** [comment]
Ah this is actually a bug tbh because I did not want them to spawn in mushroom fields. I will release a fix soon.
