### ISSUE TITLE
Config Doesn't Work

### ISSUE THREAD

**Issue by osmelious** [Safrodev/Zombified#3]
I'm hosting a server for me and some friends, and we thought that zombie spawn rates were too high.
When the config was added, I edited it so that the spawn rates would be lower, but zombies still spawned frequently.
So, I lowered it again. They were still spawning just as frequently.
Then I set the spawn rates to 0, and they were still spawning frequently.

It seems the config is either broken or doesn't have any effect.
The mod's cool, just noticed this and thought I should open an issue for it.
Any help is appreciated!

**Comment by Safrodev** [comment]
Hey thanks for letting me know. I'm not sure why the config isn't working but I may have an idea. It seems that the variables are correct but the config just doesn't reload. I'll try to get a fix out right now.
