### ISSUE TITLE
Game Crashed if Zombified Mob exist in the world.

### ISSUE THREAD

**Issue by leon7104** [Safrodev/Zombified#4]
[latest.log](https://github.com/Safrodev/Zombified/files/6884405/latest.log)

**Comment by Safrodev** [comment]
Hmmm that's weird it seems to be an issue with the miner zombie. I never got a crash when testing the mod. Would you mind telling me what your config setting is for the miner zombie?

**Comment by leon7104** [comment]
is 5.

**Comment by leon7104** [comment]
i tweaked crystal zb to 20 after crash but it still crashed
      
        "arctic_zombie_spawn_weight": 25,
	"infernal_zombie_spawn_weight": 15,
	"miner_zombie_spawn_weight": 5,
	"beserk_zombie_spawn_weight": 5,
	"sludge_zombie_spawn_weight": 30,
	"crystal_zombie_spawn_weight": 20

**Comment by Safrodev** [comment]
I don't really know what the issue is since it works fine in the dev environment. It looks like something to do with the scale of the baby miner zombie so I will have to look into that.

**Comment by leon7104** [comment]
okay thanks

**Comment by leon7104** [comment]
https://stackoverflow.com/questions/3197708/what-causes-a-java-lang-stackoverflowerror

**Comment by leon7104** [comment]
[crash-2021-08-12_16.44.43-client.txt](https://github.com/Safrodev/Zombified/files/6974092/crash-2021-08-12_16.44.43-client.txt)
crashed after loaded in crystal zombie entity exist's world

**Comment by leon7104** [comment]
hope the link above can help you fix the StackOverFlowError problem.
